name: Upload tag to PyPi

on: push

jobs:
  run action:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
    - name: updload to pypi
      uses: pypa/gh-action-pypi-publish@main
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.PYPI_SOSPCAT_TOKEN }}
